version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports: ["5432:5432"]
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  service-b:
    build: ./service-b
    environment:
      DB_HOST: db
      DB_NAME: app
      DB_USER: app
      DB_PASSWORD: app
    depends_on: [db]
    ports: ["8081:8081"]

  service-a:
    build: ./service-a
    environment:
      SERVICE_B_URL: http://service-b:8081
    depends_on: [service-b]
    ports: ["8080:8080"]

volumes:
  db-data:
